dll.c:clean
	gcc -o doubly-linked-test dll.c
	./doubly-linked-test
	rm -f doubly-linked-test
hashmap.c:clean
	gcc -o hashmap hashmap.c
	./hashmap
	rm -f hashmap
clean:
	rm -f doubly-linked-test hashmap
